# Generated by Django 4.1.4 on 2023-01-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_center_title', models.CharField(help_text='Введите название блока "О центре"', max_length=100, verbose_name='Название блока "О центре"')),
                ('about_center_description', models.TextField(help_text='Введите описание блока "О центре"', max_length=700, verbose_name='Описание блока "О центре"')),
                ('video', models.FileField(help_text='Выберите видео', max_length=254, upload_to='main_page_videos/%Y/%m/%d/', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
                'db_table': 'MainPage',
            },
        ),
    ]
