version: '3.8'

services:
  db:
    image: postgres:14.5
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - db
    command: bash -c "poetry run python manage.py migrate &&
      poetry run python manage.py collectstatic --no-input &&
      poetry run gunicorn backend.wsgi -b 0.0.0.0:8000"

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
    depends_on:
      - web

volumes:
  static_value:
  media_value:
  db_value:
