# Generated by Django 4.1.4 on 2023-01-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, help_text='Введите адрес', max_length=100, null=True, unique=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, help_text='Введите номер телефона', max_length=20, null=True, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, help_text='Введите адрес электронной почты', max_length=254, null=True, unique=True, verbose_name='Электронная почта')),
                ('working_time', models.CharField(blank=True, help_text='Введите рабочее время', max_length=16, verbose_name='Рабочее время')),
                ('working_day', models.CharField(blank=True, help_text='Введите рабочие дни', max_length=25, verbose_name='Рабочие дни')),
            ],
            options={
                'verbose_name': 'Страница "Контакты"',
                'verbose_name_plural': 'Страница "Контакты"',
                'db_table': 'ContactsPage',
            },
        ),
    ]
