# Generated by Django 4.1.4 on 2023-01-13 17:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.base.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Введите наименование', max_length=500, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'db_table': 'Job',
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование', max_length=200, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип отчета',
                'verbose_name_plural': 'Типы отчетов',
                'db_table': 'ReportType',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование', max_length=100, unique=True, verbose_name='Название отчета')),
                ('file', models.FileField(help_text='Выберите файл', max_length=254, upload_to=src.base.services.get_path_upload_report_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Файл')),
                ('reporttype_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='assistance.reporttype', verbose_name='Тип отчета')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'db_table': 'Report',
            },
        ),
    ]
